### ISSUE TITLE
Отсутствует перевод для тэга "Классицизм" в проекте "arch"

### ISSUE THREAD

**Issue by IgorPolyakov** [CupIvan/osm#4]
Добрый день, заметил что в вашем валидаторе отсутствует перевод для тэга "Классицизм" так и задумано?

https://github.com/CupIvan/osm/blob/8dd5f576dbb38abb0e82ab257261f19f788a3a89/arch/index.html#L51

**Comment by CupIvan** [comment]
сейчас сверился с wiki - действительно этот тег не описан, классицизм обозначается как neoclassicism
удалю его при очередном обновлении, спасибо :+1:
